language: python

sudo: required
cache: pip

matrix:
  include:
  - python: 3.7
    os: linux
    dist: xenial


before_install:
  - pip install --upgrade pip

install:
  - pip install -e '.[test]'
  - pip install codecov
  - pip install pytest-cov
  - pip install tox-travis

script:
  - tox